#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VNOrderData",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC11VNOrderData14AsyncOperation")
@interface AsyncOperation : NSOperation
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
@property (nonatomic, getter=isFinished) BOOL finished;
@property (nonatomic, getter=isExecuting) BOOL executing;
- (void)start;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("Cart")
@interface Cart : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end









@class CartEntry;
@class NSSet;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end









@class Tip;
@class NSIndexSet;
@class NSOrderedSet;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Tip * _Nonnull)value inTipsAtIndex:(NSInteger)idx;
- (void)removeObjectFromTipsAtIndex:(NSInteger)idx;
- (void)insertTips:(NSArray<Tip *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeTipsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInTipsAtIndex:(NSInteger)idx withObject:(Tip * _Nonnull)value;
- (void)replaceTipsAtIndexes:(NSIndexSet * _Nonnull)indexes withTips:(NSArray<Tip *> * _Nonnull)values;
- (void)addTipsObject:(Tip * _Nonnull)value;
- (void)removeTipsObject:(Tip * _Nonnull)value;
- (void)addTips:(NSOrderedSet * _Nonnull)values;
- (void)removeTips:(NSOrderedSet * _Nonnull)values;
@end



@class Menu;
@class Stand;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t deliveryFeeInCents;
@property (nonatomic) int64_t discountAmountInCents;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable lineItemsRaw;
@property (nonatomic, copy) NSString * _Nullable orderNumber;
@property (nonatomic, copy) NSString * _Nullable orderUUID;
@property (nonatomic, copy) NSString * _Nullable promoCode;
@property (nonatomic) int64_t serviceChargeInCents;
@property (nonatomic, copy) NSString * _Nullable sourceDeviceID;
@property (nonatomic) int64_t taxInCents;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable userEmail;
@property (nonatomic, copy) NSString * _Nullable userFullName;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) Stand * _Nullable stand;
@property (nonatomic, strong) NSOrderedSet * _Nullable tips;
@end


SWIFT_CLASS_NAMED("CartEntry")
@interface CartEntry : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end







@class ModifierCartEntry;

@interface CartEntry (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end

@class ExperienceEvent;
@class Item;

@interface CartEntry (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable metadata;
@property (nonatomic) int64_t quantity;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) ExperienceEvent * _Nullable event;
@property (nonatomic, strong) Item * _Nullable item;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@end


SWIFT_CLASS_NAMED("ExperienceEvent")
@interface ExperienceEvent : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ExperienceEvent (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end


@interface ExperienceEvent (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, copy) NSString * _Nullable dateText;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable displayDate;
@property (nonatomic, copy) NSString * _Nullable homeAbbreviation;
@property (nonatomic, copy) NSString * _Nullable homeCity;
@property (nonatomic, copy) NSString * _Nullable homeName;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic, copy) NSString * _Nullable specialEventText;
@property (nonatomic, copy) NSString * _Nullable timeText;
@property (nonatomic) BOOL timeToBeDecided;
@property (nonatomic, copy) NSString * _Nullable timeZone;
@property (nonatomic, copy) NSString * _Nullable visitingAbbreviation;
@property (nonatomic, copy) NSString * _Nullable visitingCity;
@property (nonatomic, copy) NSString * _Nullable visitingName;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) Menu * _Nullable menu;
@end


SWIFT_CLASS_NAMED("ExperienceItem")
@interface ExperienceItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class Metadata;

@interface ExperienceItem (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Metadata * _Nonnull)value inMetadataAtIndex:(NSInteger)idx;
- (void)removeObjectFromMetadataAtIndex:(NSInteger)idx;
- (void)insertMetadata:(NSArray<Metadata *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInMetadataAtIndex:(NSInteger)idx withObject:(Metadata * _Nonnull)value;
- (void)replaceMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes withMetadata:(NSArray<Metadata *> * _Nonnull)values;
- (void)addMetadataObject:(Metadata * _Nonnull)value;
- (void)removeMetadataObject:(Metadata * _Nonnull)value;
- (void)addMetadata:(NSOrderedSet * _Nonnull)values;
- (void)removeMetadata:(NSOrderedSet * _Nonnull)values;
@end



@class OrderSummary;

@interface ExperienceItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable activeTransferUUID;
@property (nonatomic, copy) NSDate * _Nullable availableAt;
@property (nonatomic) int64_t countdownSeconds;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSDate * _Nullable eventDate;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSDate * _Nullable expiresAt;
@property (nonatomic, copy) NSString * _Nullable globalItemUUID;
@property (nonatomic, copy) NSDate * _Nullable hiddenAt;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable instructionText;
@property (nonatomic) BOOL isRedeemable;
@property (nonatomic) BOOL isRefundable;
@property (nonatomic) BOOL isTransferable;
@property (nonatomic, copy) NSString * _Nullable itemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable recipientEmail;
@property (nonatomic, copy) NSDate * _Nullable redeemedAt;
@property (nonatomic, copy) NSString * _Nullable redemptionCode;
@property (nonatomic, copy) NSDate * _Nullable redemptionStartsAt;
@property (nonatomic, copy) NSString * _Nullable redemptionType;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSDate * _Nullable usedAt;
@property (nonatomic) double value;
@property (nonatomic, strong) NSOrderedSet * _Nullable metadata;
@property (nonatomic, strong) OrderSummary * _Nullable orderSummary;
@end


SWIFT_CLASS("_TtC11VNOrderData23GetExperienceItemParser")
@interface GetExperienceItemParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData18GetMenuItemsParser")
@interface GetMenuItemsParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData14GetMenusParser")
@interface GetMenusParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Item")
@interface Item : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntryObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntryObject:(CartEntry * _Nonnull)value;
- (void)addCartEntry:(NSSet * _Nonnull)values;
- (void)removeCartEntry:(NSSet * _Nonnull)values;
@end

@class Variant;

@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)addVariantsObject:(Variant * _Nonnull)value;
- (void)removeVariantsObject:(Variant * _Nonnull)value;
- (void)addVariants:(NSSet * _Nonnull)values;
- (void)removeVariants:(NSSet * _Nonnull)values;
@end



@class ModifierGroup;

@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ModifierGroup * _Nonnull)value inModifierGroupsAtIndex:(NSInteger)idx;
- (void)removeObjectFromModifierGroupsAtIndex:(NSInteger)idx;
- (void)insertModifierGroups:(NSArray<ModifierGroup *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeModifierGroupsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInModifierGroupsAtIndex:(NSInteger)idx withObject:(ModifierGroup * _Nonnull)value;
- (void)replaceModifierGroupsAtIndexes:(NSIndexSet * _Nonnull)indexes withModifierGroups:(NSArray<ModifierGroup *> * _Nonnull)values;
- (void)addModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)removeModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)addModifierGroups:(NSOrderedSet * _Nonnull)values;
- (void)removeModifierGroups:(NSOrderedSet * _Nonnull)values;
@end


@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Metadata * _Nonnull)value inMetadataAtIndex:(NSInteger)idx;
- (void)removeObjectFromMetadataAtIndex:(NSInteger)idx;
- (void)insertMetadata:(NSArray<Metadata *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInMetadataAtIndex:(NSInteger)idx withObject:(Metadata * _Nonnull)value;
- (void)replaceMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes withMetadata:(NSArray<Metadata *> * _Nonnull)values;
- (void)addMetadataObject:(Metadata * _Nonnull)value;
- (void)removeMetadataObject:(Metadata * _Nonnull)value;
- (void)addMetadata:(NSOrderedSet * _Nonnull)values;
- (void)removeMetadata:(NSOrderedSet * _Nonnull)values;
@end

@class ItemCategory;

@interface Item (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryUUID;
@property (nonatomic) BOOL comboMeal;
@property (nonatomic) int64_t defaultPriceInCents;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable ingredients;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic) BOOL isModifier;
@property (nonatomic) BOOL isServiceFeeItem;
@property (nonatomic, copy) NSString * _Nullable marketingDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t orderMaxAmount;
@property (nonatomic, copy) NSString * _Nullable qrCode;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable cartEntry;
@property (nonatomic, strong) ItemCategory * _Nullable itemCategory;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) NSOrderedSet * _Nullable metadata;
@property (nonatomic, strong) NSOrderedSet * _Nullable modifierGroups;
@property (nonatomic, strong) NSSet * _Nullable variants;
@end


SWIFT_CLASS_NAMED("ItemCategory")
@interface ItemCategory : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ItemCategory (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end


@interface ItemCategory (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryType;
@property (nonatomic) BOOL featured;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic) BOOL isModifier;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t sortOrder;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) Stand * _Nullable stand;
@end


SWIFT_CLASS_NAMED("LineItem")
@interface LineItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class ModifierLineItem;

@interface LineItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifiersObject:(ModifierLineItem * _Nonnull)value;
- (void)removeModifiersObject:(ModifierLineItem * _Nonnull)value;
- (void)addModifiers:(NSSet * _Nonnull)values;
- (void)removeModifiers:(NSSet * _Nonnull)values;
@end


@interface LineItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic, copy) NSString * _Nullable itemUUID;
@property (nonatomic, copy) NSString * _Nullable menuItemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable parentLineItemUUID;
@property (nonatomic, copy) NSString * _Nullable paymentType;
@property (nonatomic) double price;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t quantity;
@property (nonatomic, copy) NSString * _Nullable specialType;
@property (nonatomic) int64_t taxAmountInCents;
@property (nonatomic) double total;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable modifiers;
@property (nonatomic, strong) OrderSummary * _Nullable orderSummary;
@end


SWIFT_CLASS_NAMED("Menu")
@interface Menu : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)removeCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)addCategories:(NSSet * _Nonnull)values;
- (void)removeCategories:(NSSet * _Nonnull)values;
@end


@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addEventsObject:(ExperienceEvent * _Nonnull)value;
- (void)removeEventsObject:(ExperienceEvent * _Nonnull)value;
- (void)addEvents:(NSSet * _Nonnull)values;
- (void)removeEvents:(NSSet * _Nonnull)values;
@end


@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end




@interface Menu (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t alcoholLimit;
@property (nonatomic, copy) NSString * _Nullable alcoholLimitMessage;
@property (nonatomic) BOOL canOrderAhead;
@property (nonatomic) BOOL canOrderNow;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic) BOOL hasAlcohol;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic) BOOL isAvailible;
@property (nonatomic, copy) NSString * _Nullable longDescriptionText;
@property (nonatomic) int64_t maxOrderAmountInDollars;
@property (nonatomic, copy) NSString * _Nullable menuDescription;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable serviceType;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic) double taxRate;
@property (nonatomic) BOOL usesQRCode;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) NSSet * _Nullable categories;
@property (nonatomic, strong) NSSet * _Nullable events;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) Stand * _Nullable stand;
@end


SWIFT_CLASS_NAMED("Metadata")
@interface Metadata : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Metadata (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable dataType;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
@property (nonatomic) BOOL hasRestriction;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) int64_t maxValue;
@property (nonatomic) int64_t minValue;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable operatorText;
@property (nonatomic) int64_t value;
@property (nonatomic, strong) ExperienceItem * _Nullable experienceItem;
@property (nonatomic, strong) Item * _Nullable item;
@end


SWIFT_CLASS_NAMED("ModifierCartEntry")
@interface ModifierCartEntry : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end








@interface ModifierCartEntry (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end

@class ModifierItem;

@interface ModifierCartEntry (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) int64_t quantity;
@property (nonatomic) int64_t secondaryPriceThresholdCount;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) ModifierGroup * _Nullable modifierGroup;
@property (nonatomic, strong) ModifierItem * _Nullable modifierItem;
@end


SWIFT_CLASS_NAMED("ModifierGroup")
@interface ModifierGroup : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ModifierItem * _Nonnull)value inModifierItemsAtIndex:(NSInteger)idx;
- (void)removeObjectFromModifierItemsAtIndex:(NSInteger)idx;
- (void)insertModifierItems:(NSArray<ModifierItem *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeModifierItemsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInModifierItemsAtIndex:(NSInteger)idx withObject:(ModifierItem * _Nonnull)value;
- (void)replaceModifierItemsAtIndexes:(NSIndexSet * _Nonnull)indexes withModifierItems:(NSArray<ModifierItem *> * _Nonnull)values;
- (void)addModifierItemsObject:(ModifierItem * _Nonnull)value;
- (void)removeModifierItemsObject:(ModifierItem * _Nonnull)value;
- (void)addModifierItems:(NSOrderedSet * _Nonnull)values;
- (void)removeModifierItems:(NSOrderedSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isRequiredSelectionMet;
@property (nonatomic, copy) NSString * _Nullable itemIdentifier;
@property (nonatomic) int64_t maximumSelectionCount;
@property (nonatomic) int64_t minimumSelectionCount;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL requiresSelection;
@property (nonatomic) int64_t secondaryPriceThresholdCount;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@property (nonatomic, strong) NSOrderedSet * _Nullable modifierItems;
@end


SWIFT_CLASS_NAMED("ModifierItem")
@interface ModifierItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)removeModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)addModifierGroups:(NSSet * _Nonnull)values;
- (void)removeModifierGroups:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addVariantsObject:(Variant * _Nonnull)value;
- (void)removeVariantsObject:(Variant * _Nonnull)value;
- (void)addVariants:(NSSet * _Nonnull)values;
- (void)removeVariants:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryUUID;
@property (nonatomic) BOOL comboMeal;
@property (nonatomic) int64_t defaultPriceInCents;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable ingredients;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic) BOOL isModifier;
@property (nonatomic) BOOL isServiceFeeItem;
@property (nonatomic, copy) NSString * _Nullable marketingDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t orderMaxAmount;
@property (nonatomic, copy) NSString * _Nullable qrCode;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@property (nonatomic, strong) NSSet * _Nullable modifierGroups;
@property (nonatomic, strong) NSSet * _Nullable variants;
@end


SWIFT_CLASS_NAMED("ModifierLineItem")
@interface ModifierLineItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ModifierLineItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic, copy) NSString * _Nullable menuItemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t quantity;
@property (nonatomic, strong) LineItem * _Nullable parentLineItem;
@end




@interface NSFetchedResultsController<ResultType> (SWIFT_EXTENSION(VNOrderData))
- (NSManagedObject * _Nonnull)objectForKeyedSubscript:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end







@class NSString;

@interface NSManagedObject (SWIFT_EXTENSION(VNOrderData))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull coreDataEntityName;)
+ (NSString * _Nonnull)coreDataEntityName SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS_NAMED("OrderSummary")
@interface OrderSummary : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
- (void)addLineItemsObject:(LineItem * _Nonnull)value;
- (void)removeLineItemsObject:(LineItem * _Nonnull)value;
- (void)addLineItems:(NSSet * _Nonnull)values;
- (void)removeLineItems:(NSSet * _Nonnull)values;
@end


@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
- (void)addExperienceItemsObject:(ExperienceItem * _Nonnull)value;
- (void)removeExperienceItemsObject:(ExperienceItem * _Nonnull)value;
- (void)addExperienceItems:(NSSet * _Nonnull)values;
- (void)removeExperienceItems:(NSSet * _Nonnull)values;
@end






@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSDate * _Nullable canceledAt;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable creditCardType;
@property (nonatomic) double deliveryFee;
@property (nonatomic) double discountAmountInCents;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSString * _Nullable fulfillmentDate;
@property (nonatomic, copy) NSString * _Nullable fulfillmentSlot;
@property (nonatomic) BOOL hasQRCode;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable instructionsText;
@property (nonatomic) BOOL isCancellable;
@property (nonatomic) BOOL isUserRefundable;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable itemNames;
@property (nonatomic, copy) NSString * _Nullable lastFour;
@property (nonatomic) int64_t lineItemCount;
@property (nonatomic, copy) NSString * _Nullable orderLocation;
@property (nonatomic, copy) NSString * _Nullable orderNumber;
@property (nonatomic, copy) NSDate * _Nullable paymentAuthorizedAt;
@property (nonatomic, copy) NSDate * _Nullable paymentRefundedAt;
@property (nonatomic, copy) NSDate * _Nullable paymentSettledAt;
@property (nonatomic, copy) NSDate * _Nullable paymentVoidedAt;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic) int64_t quantity;
@property (nonatomic, copy) NSDate * _Nullable refundedAt;
@property (nonatomic, copy) NSString * _Nullable revenueCenterMenuUUID;
@property (nonatomic, copy) NSString * _Nullable revenueCenterName;
@property (nonatomic, copy) NSString * _Nullable revenueCenterUUID;
@property (nonatomic, copy) NSString * _Nullable row;
@property (nonatomic, copy) NSString * _Nullable seat;
@property (nonatomic, copy) NSString * _Nullable section;
@property (nonatomic) double serviceCharge;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable stateDescription;
@property (nonatomic, copy) NSString * _Nullable stateDisplayName;
@property (nonatomic) double subtotal;
@property (nonatomic) BOOL success;
@property (nonatomic) double tax;
@property (nonatomic) double taxRate;
@property (nonatomic) double tip;
@property (nonatomic) double total;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable totalsWithPaymentType;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable usageType;
@property (nonatomic, copy) NSString * _Nullable userNotes;
@property (nonatomic, copy) NSString * _Nullable userUUID;
@property (nonatomic, strong) NSSet * _Nullable experienceItems;
@property (nonatomic, strong) NSSet * _Nullable lineItems;
@end


SWIFT_CLASS_NAMED("Payment")
@interface Payment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Payment (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t taxAmountInCents;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS("_TtC11VNOrderData24PostExperienceItemParser")
@interface PostExperienceItemParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData21ReloadStandsOperation")
@interface ReloadStandsOperation : AsyncOperation
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Used for the <code>line_items</code> array in the reorder response
SWIFT_CLASS("_TtC11VNOrderData14RemoteLineItem")
@interface RemoteLineItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VNOrderData28RemoteOrderAheadAvailability")
@interface RemoteOrderAheadAvailability : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Sale")
@interface Sale : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Sale (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int32_t distance_threshold;
@property (nonatomic, copy) NSDate * _Nullable ends_at;
@property (nonatomic, copy) NSString * _Nullable group;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable item_identifier;
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic) double lat;
@property (nonatomic, getter=long, setter=setLong:) double long_;
@property (nonatomic) double price;
@property (nonatomic, copy) NSDate * _Nullable starts_at;
@property (nonatomic, strong) Variant * _Nullable variant;
@end


SWIFT_CLASS_NAMED("Seat")
@interface Seat : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Seat (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end




@interface Seat (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable aisleIdentifiers;
@property (nonatomic, copy) NSDate * _Nullable created;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isSuite;
@property (nonatomic, copy) NSString * _Nullable revenueCenterIdentifier;
@property (nonatomic, copy) NSString * _Nullable row;
@property (nonatomic, copy) NSString * _Nullable seat;
@property (nonatomic, copy) NSString * _Nullable section;
@end


SWIFT_CLASS_NAMED("Stand")
@interface Stand : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Stand (SWIFT_EXTENSION(VNOrderData))
- (void)addMenusObject:(Menu * _Nonnull)value;
- (void)removeMenusObject:(Menu * _Nonnull)value;
- (void)addMenus:(NSSet * _Nonnull)values;
- (void)removeMenus:(NSSet * _Nonnull)values;
@end


@interface Stand (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ItemCategory * _Nonnull)value inItemCategoriesAtIndex:(NSInteger)idx;
- (void)removeObjectFromItemCategoriesAtIndex:(NSInteger)idx;
- (void)insertItemCategories:(NSArray<ItemCategory *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeItemCategoriesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInItemCategoriesAtIndex:(NSInteger)idx withObject:(ItemCategory * _Nonnull)value;
- (void)replaceItemCategoriesAtIndexes:(NSIndexSet * _Nonnull)indexes withItemCategories:(NSArray<ItemCategory *> * _Nonnull)values;
- (void)addItemCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)removeItemCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)addItemCategories:(NSOrderedSet * _Nonnull)values;
- (void)removeItemCategories:(NSOrderedSet * _Nonnull)values;
@end


@interface Stand (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable alcoholLimitMessage;
@property (nonatomic, copy) NSString * _Nullable alcoholWarningMessage;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable longDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable serviceTypes;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, copy) NSString * _Nullable venueDisplayName;
@property (nonatomic, copy) NSString * _Nullable venueOrganizationName;
@property (nonatomic) int64_t venueSortOrder;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) NSOrderedSet * _Nullable itemCategories;
@property (nonatomic, strong) NSSet * _Nullable menus;
@end


SWIFT_CLASS_NAMED("Tip")
@interface Tip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

@interface Tip (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, strong) NSNumber * _Nullable amountInCents;
@property (nonatomic, copy) NSString * _Nullable displayText;
@property (nonatomic) BOOL isCustom;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, strong) Cart * _Nullable cart;
@end


/// A class backed by CoreData that serves as the data layer and source of truth for driving <code>VNOrderUI</code>.
SWIFT_CLASS("_TtC11VNOrderData11VNOrderData")
@interface VNOrderData : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VNOrderData * _Nonnull shared;)
+ (VNOrderData * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface VNOrderData (SWIFT_EXTENSION(VNOrderData))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull classStringName;)
+ (NSString * _Nonnull)classStringName SWIFT_WARN_UNUSED_RESULT;
@end




@interface VNOrderData (SWIFT_EXTENSION(VNOrderData))
- (void)reloadStandsWithCompletion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("Variant")
@interface Variant : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Variant (SWIFT_EXTENSION(VNOrderData))
- (void)addSalesObject:(Sale * _Nonnull)value;
- (void)removeSalesObject:(Sale * _Nonnull)value;
- (void)addSales:(NSSet * _Nonnull)values;
- (void)removeSales:(NSSet * _Nonnull)values;
@end




@interface Variant (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable availableAt;
@property (nonatomic, copy) NSString * _Nullable categoryName;
@property (nonatomic) int64_t defaultQuantity;
@property (nonatomic, copy) NSString * _Nullable eventName;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic) int64_t experiencePrice;
@property (nonatomic, copy) NSString * _Nullable expiresAt;
@property (nonatomic, copy) NSString * _Nullable globaltemId;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable inventoryState;
@property (nonatomic) BOOL isModifier;
@property (nonatomic, copy) NSString * _Nullable linkedMenuItemIdentifier;
@property (nonatomic, copy) NSString * _Nullable merchantId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t onHandQuantity;
@property (nonatomic) int64_t priceAfterThresholdInCents;
@property (nonatomic) int64_t priceInCents;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t purchaseLimit;
@property (nonatomic, copy) NSString * _Nullable redemptionStartsAt;
@property (nonatomic, copy) NSString * _Nullable saleId;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable saleIds;
@property (nonatomic, strong) Item * _Nullable item;
@property (nonatomic, strong) ModifierItem * _Nullable modifierItem;
@property (nonatomic, strong) NSSet * _Nullable sales;
@end


SWIFT_CLASS_NAMED("Venue")
@interface Venue : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Venue (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable displayName;
@property (nonatomic, copy) NSString * _Nullable organizationName;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#else
// Generated by Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VNOrderData",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC11VNOrderData14AsyncOperation")
@interface AsyncOperation : NSOperation
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
@property (nonatomic, getter=isFinished) BOOL finished;
@property (nonatomic, getter=isExecuting) BOOL executing;
- (void)start;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("Cart")
@interface Cart : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end









@class CartEntry;
@class NSSet;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end









@class Tip;
@class NSIndexSet;
@class NSOrderedSet;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Tip * _Nonnull)value inTipsAtIndex:(NSInteger)idx;
- (void)removeObjectFromTipsAtIndex:(NSInteger)idx;
- (void)insertTips:(NSArray<Tip *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeTipsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInTipsAtIndex:(NSInteger)idx withObject:(Tip * _Nonnull)value;
- (void)replaceTipsAtIndexes:(NSIndexSet * _Nonnull)indexes withTips:(NSArray<Tip *> * _Nonnull)values;
- (void)addTipsObject:(Tip * _Nonnull)value;
- (void)removeTipsObject:(Tip * _Nonnull)value;
- (void)addTips:(NSOrderedSet * _Nonnull)values;
- (void)removeTips:(NSOrderedSet * _Nonnull)values;
@end



@class Menu;
@class Stand;

@interface Cart (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t deliveryFeeInCents;
@property (nonatomic) int64_t discountAmountInCents;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable lineItemsRaw;
@property (nonatomic, copy) NSString * _Nullable orderNumber;
@property (nonatomic, copy) NSString * _Nullable orderUUID;
@property (nonatomic, copy) NSString * _Nullable promoCode;
@property (nonatomic) int64_t serviceChargeInCents;
@property (nonatomic, copy) NSString * _Nullable sourceDeviceID;
@property (nonatomic) int64_t taxInCents;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable userEmail;
@property (nonatomic, copy) NSString * _Nullable userFullName;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) Stand * _Nullable stand;
@property (nonatomic, strong) NSOrderedSet * _Nullable tips;
@end


SWIFT_CLASS_NAMED("CartEntry")
@interface CartEntry : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end







@class ModifierCartEntry;

@interface CartEntry (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end

@class ExperienceEvent;
@class Item;

@interface CartEntry (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable metadata;
@property (nonatomic) int64_t quantity;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) ExperienceEvent * _Nullable event;
@property (nonatomic, strong) Item * _Nullable item;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@end


SWIFT_CLASS_NAMED("ExperienceEvent")
@interface ExperienceEvent : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ExperienceEvent (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end


@interface ExperienceEvent (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, copy) NSString * _Nullable dateText;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable displayDate;
@property (nonatomic, copy) NSString * _Nullable homeAbbreviation;
@property (nonatomic, copy) NSString * _Nullable homeCity;
@property (nonatomic, copy) NSString * _Nullable homeName;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic, copy) NSString * _Nullable specialEventText;
@property (nonatomic, copy) NSString * _Nullable timeText;
@property (nonatomic) BOOL timeToBeDecided;
@property (nonatomic, copy) NSString * _Nullable timeZone;
@property (nonatomic, copy) NSString * _Nullable visitingAbbreviation;
@property (nonatomic, copy) NSString * _Nullable visitingCity;
@property (nonatomic, copy) NSString * _Nullable visitingName;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) Menu * _Nullable menu;
@end


SWIFT_CLASS_NAMED("ExperienceItem")
@interface ExperienceItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class Metadata;

@interface ExperienceItem (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Metadata * _Nonnull)value inMetadataAtIndex:(NSInteger)idx;
- (void)removeObjectFromMetadataAtIndex:(NSInteger)idx;
- (void)insertMetadata:(NSArray<Metadata *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInMetadataAtIndex:(NSInteger)idx withObject:(Metadata * _Nonnull)value;
- (void)replaceMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes withMetadata:(NSArray<Metadata *> * _Nonnull)values;
- (void)addMetadataObject:(Metadata * _Nonnull)value;
- (void)removeMetadataObject:(Metadata * _Nonnull)value;
- (void)addMetadata:(NSOrderedSet * _Nonnull)values;
- (void)removeMetadata:(NSOrderedSet * _Nonnull)values;
@end



@class OrderSummary;

@interface ExperienceItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable activeTransferUUID;
@property (nonatomic, copy) NSDate * _Nullable availableAt;
@property (nonatomic) int64_t countdownSeconds;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSDate * _Nullable eventDate;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSDate * _Nullable expiresAt;
@property (nonatomic, copy) NSString * _Nullable globalItemUUID;
@property (nonatomic, copy) NSDate * _Nullable hiddenAt;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable instructionText;
@property (nonatomic) BOOL isRedeemable;
@property (nonatomic) BOOL isRefundable;
@property (nonatomic) BOOL isTransferable;
@property (nonatomic, copy) NSString * _Nullable itemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable recipientEmail;
@property (nonatomic, copy) NSDate * _Nullable redeemedAt;
@property (nonatomic, copy) NSString * _Nullable redemptionCode;
@property (nonatomic, copy) NSDate * _Nullable redemptionStartsAt;
@property (nonatomic, copy) NSString * _Nullable redemptionType;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSDate * _Nullable usedAt;
@property (nonatomic) double value;
@property (nonatomic, strong) NSOrderedSet * _Nullable metadata;
@property (nonatomic, strong) OrderSummary * _Nullable orderSummary;
@end


SWIFT_CLASS("_TtC11VNOrderData23GetExperienceItemParser")
@interface GetExperienceItemParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData18GetMenuItemsParser")
@interface GetMenuItemsParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData14GetMenusParser")
@interface GetMenusParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Item")
@interface Item : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntryObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntryObject:(CartEntry * _Nonnull)value;
- (void)addCartEntry:(NSSet * _Nonnull)values;
- (void)removeCartEntry:(NSSet * _Nonnull)values;
@end

@class Variant;

@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)addVariantsObject:(Variant * _Nonnull)value;
- (void)removeVariantsObject:(Variant * _Nonnull)value;
- (void)addVariants:(NSSet * _Nonnull)values;
- (void)removeVariants:(NSSet * _Nonnull)values;
@end



@class ModifierGroup;

@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ModifierGroup * _Nonnull)value inModifierGroupsAtIndex:(NSInteger)idx;
- (void)removeObjectFromModifierGroupsAtIndex:(NSInteger)idx;
- (void)insertModifierGroups:(NSArray<ModifierGroup *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeModifierGroupsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInModifierGroupsAtIndex:(NSInteger)idx withObject:(ModifierGroup * _Nonnull)value;
- (void)replaceModifierGroupsAtIndexes:(NSIndexSet * _Nonnull)indexes withModifierGroups:(NSArray<ModifierGroup *> * _Nonnull)values;
- (void)addModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)removeModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)addModifierGroups:(NSOrderedSet * _Nonnull)values;
- (void)removeModifierGroups:(NSOrderedSet * _Nonnull)values;
@end


@interface Item (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(Metadata * _Nonnull)value inMetadataAtIndex:(NSInteger)idx;
- (void)removeObjectFromMetadataAtIndex:(NSInteger)idx;
- (void)insertMetadata:(NSArray<Metadata *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInMetadataAtIndex:(NSInteger)idx withObject:(Metadata * _Nonnull)value;
- (void)replaceMetadataAtIndexes:(NSIndexSet * _Nonnull)indexes withMetadata:(NSArray<Metadata *> * _Nonnull)values;
- (void)addMetadataObject:(Metadata * _Nonnull)value;
- (void)removeMetadataObject:(Metadata * _Nonnull)value;
- (void)addMetadata:(NSOrderedSet * _Nonnull)values;
- (void)removeMetadata:(NSOrderedSet * _Nonnull)values;
@end

@class ItemCategory;

@interface Item (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryUUID;
@property (nonatomic) BOOL comboMeal;
@property (nonatomic) int64_t defaultPriceInCents;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable ingredients;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic) BOOL isModifier;
@property (nonatomic) BOOL isServiceFeeItem;
@property (nonatomic, copy) NSString * _Nullable marketingDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t orderMaxAmount;
@property (nonatomic, copy) NSString * _Nullable qrCode;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable cartEntry;
@property (nonatomic, strong) ItemCategory * _Nullable itemCategory;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) NSOrderedSet * _Nullable metadata;
@property (nonatomic, strong) NSOrderedSet * _Nullable modifierGroups;
@property (nonatomic, strong) NSSet * _Nullable variants;
@end


SWIFT_CLASS_NAMED("ItemCategory")
@interface ItemCategory : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ItemCategory (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end


@interface ItemCategory (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryType;
@property (nonatomic) BOOL featured;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic) BOOL isModifier;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t sortOrder;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) Menu * _Nullable menu;
@property (nonatomic, strong) Stand * _Nullable stand;
@end


SWIFT_CLASS_NAMED("LineItem")
@interface LineItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@class ModifierLineItem;

@interface LineItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifiersObject:(ModifierLineItem * _Nonnull)value;
- (void)removeModifiersObject:(ModifierLineItem * _Nonnull)value;
- (void)addModifiers:(NSSet * _Nonnull)values;
- (void)removeModifiers:(NSSet * _Nonnull)values;
@end


@interface LineItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic, copy) NSString * _Nullable itemUUID;
@property (nonatomic, copy) NSString * _Nullable menuItemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable parentLineItemUUID;
@property (nonatomic, copy) NSString * _Nullable paymentType;
@property (nonatomic) double price;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t quantity;
@property (nonatomic, copy) NSString * _Nullable specialType;
@property (nonatomic) int64_t taxAmountInCents;
@property (nonatomic) double total;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable modifiers;
@property (nonatomic, strong) OrderSummary * _Nullable orderSummary;
@end


SWIFT_CLASS_NAMED("Menu")
@interface Menu : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)removeCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)addCategories:(NSSet * _Nonnull)values;
- (void)removeCategories:(NSSet * _Nonnull)values;
@end


@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addEventsObject:(ExperienceEvent * _Nonnull)value;
- (void)removeEventsObject:(ExperienceEvent * _Nonnull)value;
- (void)addEvents:(NSSet * _Nonnull)values;
- (void)removeEvents:(NSSet * _Nonnull)values;
@end


@interface Menu (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end




@interface Menu (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t alcoholLimit;
@property (nonatomic, copy) NSString * _Nullable alcoholLimitMessage;
@property (nonatomic) BOOL canOrderAhead;
@property (nonatomic) BOOL canOrderNow;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic) BOOL hasAlcohol;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic) BOOL isAvailible;
@property (nonatomic, copy) NSString * _Nullable longDescriptionText;
@property (nonatomic) int64_t maxOrderAmountInDollars;
@property (nonatomic, copy) NSString * _Nullable menuDescription;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable serviceType;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic) double taxRate;
@property (nonatomic) BOOL usesQRCode;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) NSSet * _Nullable categories;
@property (nonatomic, strong) NSSet * _Nullable events;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) Stand * _Nullable stand;
@end


SWIFT_CLASS_NAMED("Metadata")
@interface Metadata : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Metadata (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable dataType;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable errorMessage;
@property (nonatomic) BOOL hasRestriction;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) int64_t maxValue;
@property (nonatomic) int64_t minValue;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable operatorText;
@property (nonatomic) int64_t value;
@property (nonatomic, strong) ExperienceItem * _Nullable experienceItem;
@property (nonatomic, strong) Item * _Nullable item;
@end


SWIFT_CLASS_NAMED("ModifierCartEntry")
@interface ModifierCartEntry : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end








@interface ModifierCartEntry (SWIFT_EXTENSION(VNOrderData))
- (void)addCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)removeCartEntriesObject:(CartEntry * _Nonnull)value;
- (void)addCartEntries:(NSSet * _Nonnull)values;
- (void)removeCartEntries:(NSSet * _Nonnull)values;
@end

@class ModifierItem;

@interface ModifierCartEntry (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) int64_t quantity;
@property (nonatomic) int64_t secondaryPriceThresholdCount;
@property (nonatomic, strong) NSSet * _Nullable cartEntries;
@property (nonatomic, strong) ModifierGroup * _Nullable modifierGroup;
@property (nonatomic, strong) ModifierItem * _Nullable modifierItem;
@end


SWIFT_CLASS_NAMED("ModifierGroup")
@interface ModifierGroup : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)addItemsObject:(Item * _Nonnull)value;
- (void)removeItemsObject:(Item * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ModifierItem * _Nonnull)value inModifierItemsAtIndex:(NSInteger)idx;
- (void)removeObjectFromModifierItemsAtIndex:(NSInteger)idx;
- (void)insertModifierItems:(NSArray<ModifierItem *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeModifierItemsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInModifierItemsAtIndex:(NSInteger)idx withObject:(ModifierItem * _Nonnull)value;
- (void)replaceModifierItemsAtIndexes:(NSIndexSet * _Nonnull)indexes withModifierItems:(NSArray<ModifierItem *> * _Nonnull)values;
- (void)addModifierItemsObject:(ModifierItem * _Nonnull)value;
- (void)removeModifierItemsObject:(ModifierItem * _Nonnull)value;
- (void)addModifierItems:(NSOrderedSet * _Nonnull)values;
- (void)removeModifierItems:(NSOrderedSet * _Nonnull)values;
@end


@interface ModifierGroup (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isRequiredSelectionMet;
@property (nonatomic, copy) NSString * _Nullable itemIdentifier;
@property (nonatomic) int64_t maximumSelectionCount;
@property (nonatomic) int64_t minimumSelectionCount;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL requiresSelection;
@property (nonatomic) int64_t secondaryPriceThresholdCount;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable items;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@property (nonatomic, strong) NSOrderedSet * _Nullable modifierItems;
@end


SWIFT_CLASS_NAMED("ModifierItem")
@interface ModifierItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)removeModifierGroupsObject:(ModifierGroup * _Nonnull)value;
- (void)addModifierGroups:(NSSet * _Nonnull)values;
- (void)removeModifierGroups:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)removeModifierCartEntriesObject:(ModifierCartEntry * _Nonnull)value;
- (void)addModifierCartEntries:(NSSet * _Nonnull)values;
- (void)removeModifierCartEntries:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
- (void)addVariantsObject:(Variant * _Nonnull)value;
- (void)removeVariantsObject:(Variant * _Nonnull)value;
- (void)addVariants:(NSSet * _Nonnull)values;
- (void)removeVariants:(NSSet * _Nonnull)values;
@end


@interface ModifierItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable categoryUUID;
@property (nonatomic) BOOL comboMeal;
@property (nonatomic) int64_t defaultPriceInCents;
@property (nonatomic, copy) NSString * _Nullable descriptionText;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable ingredients;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic) BOOL isModifier;
@property (nonatomic) BOOL isServiceFeeItem;
@property (nonatomic, copy) NSString * _Nullable marketingDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t orderMaxAmount;
@property (nonatomic, copy) NSString * _Nullable qrCode;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, strong) NSSet * _Nullable modifierCartEntries;
@property (nonatomic, strong) NSSet * _Nullable modifierGroups;
@property (nonatomic, strong) NSSet * _Nullable variants;
@end


SWIFT_CLASS_NAMED("ModifierLineItem")
@interface ModifierLineItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ModifierLineItem (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isAlcohol;
@property (nonatomic, copy) NSString * _Nullable menuItemUUID;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t quantity;
@property (nonatomic, strong) LineItem * _Nullable parentLineItem;
@end




@interface NSFetchedResultsController<ResultType> (SWIFT_EXTENSION(VNOrderData))
- (NSManagedObject * _Nonnull)objectForKeyedSubscript:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end







@class NSString;

@interface NSManagedObject (SWIFT_EXTENSION(VNOrderData))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSString * _Nonnull coreDataEntityName;)
+ (NSString * _Nonnull)coreDataEntityName SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS_NAMED("OrderSummary")
@interface OrderSummary : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
- (void)addLineItemsObject:(LineItem * _Nonnull)value;
- (void)removeLineItemsObject:(LineItem * _Nonnull)value;
- (void)addLineItems:(NSSet * _Nonnull)values;
- (void)removeLineItems:(NSSet * _Nonnull)values;
@end


@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
- (void)addExperienceItemsObject:(ExperienceItem * _Nonnull)value;
- (void)removeExperienceItemsObject:(ExperienceItem * _Nonnull)value;
- (void)addExperienceItems:(NSSet * _Nonnull)values;
- (void)removeExperienceItems:(NSSet * _Nonnull)values;
@end






@interface OrderSummary (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSDate * _Nullable canceledAt;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable creditCardType;
@property (nonatomic) double deliveryFee;
@property (nonatomic) double discountAmountInCents;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic, copy) NSString * _Nullable fulfillmentDate;
@property (nonatomic, copy) NSString * _Nullable fulfillmentSlot;
@property (nonatomic) BOOL hasQRCode;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable instructionsText;
@property (nonatomic) BOOL isCancellable;
@property (nonatomic) BOOL isUserRefundable;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable itemNames;
@property (nonatomic, copy) NSString * _Nullable lastFour;
@property (nonatomic) int64_t lineItemCount;
@property (nonatomic, copy) NSString * _Nullable orderLocation;
@property (nonatomic, copy) NSString * _Nullable orderNumber;
@property (nonatomic, copy) NSDate * _Nullable paymentAuthorizedAt;
@property (nonatomic, copy) NSDate * _Nullable paymentRefundedAt;
@property (nonatomic, copy) NSDate * _Nullable paymentSettledAt;
@property (nonatomic, copy) NSDate * _Nullable paymentVoidedAt;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic) int64_t quantity;
@property (nonatomic, copy) NSDate * _Nullable refundedAt;
@property (nonatomic, copy) NSString * _Nullable revenueCenterMenuUUID;
@property (nonatomic, copy) NSString * _Nullable revenueCenterName;
@property (nonatomic, copy) NSString * _Nullable revenueCenterUUID;
@property (nonatomic, copy) NSString * _Nullable row;
@property (nonatomic, copy) NSString * _Nullable seat;
@property (nonatomic, copy) NSString * _Nullable section;
@property (nonatomic) double serviceCharge;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable stateDescription;
@property (nonatomic, copy) NSString * _Nullable stateDisplayName;
@property (nonatomic) double subtotal;
@property (nonatomic) BOOL success;
@property (nonatomic) double tax;
@property (nonatomic) double taxRate;
@property (nonatomic) double tip;
@property (nonatomic) double total;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable totalsWithPaymentType;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable usageType;
@property (nonatomic, copy) NSString * _Nullable userNotes;
@property (nonatomic, copy) NSString * _Nullable userUUID;
@property (nonatomic, strong) NSSet * _Nullable experienceItems;
@property (nonatomic, strong) NSSet * _Nullable lineItems;
@end


SWIFT_CLASS_NAMED("Payment")
@interface Payment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Payment (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int64_t taxAmountInCents;
@property (nonatomic) int64_t totalAmountInCents;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS("_TtC11VNOrderData24PostExperienceItemParser")
@interface PostExperienceItemParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11VNOrderData21ReloadStandsOperation")
@interface ReloadStandsOperation : AsyncOperation
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Used for the <code>line_items</code> array in the reorder response
SWIFT_CLASS("_TtC11VNOrderData14RemoteLineItem")
@interface RemoteLineItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11VNOrderData28RemoteOrderAheadAvailability")
@interface RemoteOrderAheadAvailability : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("Sale")
@interface Sale : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Sale (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic) int32_t distance_threshold;
@property (nonatomic, copy) NSDate * _Nullable ends_at;
@property (nonatomic, copy) NSString * _Nullable group;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable item_identifier;
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic) double lat;
@property (nonatomic, getter=long, setter=setLong:) double long_;
@property (nonatomic) double price;
@property (nonatomic, copy) NSDate * _Nullable starts_at;
@property (nonatomic, strong) Variant * _Nullable variant;
@end


SWIFT_CLASS_NAMED("Seat")
@interface Seat : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Seat (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end




@interface Seat (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable aisleIdentifiers;
@property (nonatomic, copy) NSDate * _Nullable created;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic) BOOL isSuite;
@property (nonatomic, copy) NSString * _Nullable revenueCenterIdentifier;
@property (nonatomic, copy) NSString * _Nullable row;
@property (nonatomic, copy) NSString * _Nullable seat;
@property (nonatomic, copy) NSString * _Nullable section;
@end


SWIFT_CLASS_NAMED("Stand")
@interface Stand : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface Stand (SWIFT_EXTENSION(VNOrderData))
- (void)addMenusObject:(Menu * _Nonnull)value;
- (void)removeMenusObject:(Menu * _Nonnull)value;
- (void)addMenus:(NSSet * _Nonnull)values;
- (void)removeMenus:(NSSet * _Nonnull)values;
@end


@interface Stand (SWIFT_EXTENSION(VNOrderData))
- (void)insertObject:(ItemCategory * _Nonnull)value inItemCategoriesAtIndex:(NSInteger)idx;
- (void)removeObjectFromItemCategoriesAtIndex:(NSInteger)idx;
- (void)insertItemCategories:(NSArray<ItemCategory *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeItemCategoriesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInItemCategoriesAtIndex:(NSInteger)idx withObject:(ItemCategory * _Nonnull)value;
- (void)replaceItemCategoriesAtIndexes:(NSIndexSet * _Nonnull)indexes withItemCategories:(NSArray<ItemCategory *> * _Nonnull)values;
- (void)addItemCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)removeItemCategoriesObject:(ItemCategory * _Nonnull)value;
- (void)addItemCategories:(NSOrderedSet * _Nonnull)values;
- (void)removeItemCategories:(NSOrderedSet * _Nonnull)values;
@end


@interface Stand (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable alcoholLimitMessage;
@property (nonatomic, copy) NSString * _Nullable alcoholWarningMessage;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSURL * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable longDescriptionText;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable serviceTypes;
@property (nonatomic, copy) NSString * _Nullable shortDescriptionText;
@property (nonatomic) int64_t sortIndex;
@property (nonatomic, copy) NSString * _Nullable venueDisplayName;
@property (nonatomic, copy) NSString * _Nullable venueOrganizationName;
@property (nonatomic) int64_t venueSortOrder;
@property (nonatomic, strong) Cart * _Nullable cart;
@property (nonatomic, strong) NSOrderedSet * _Nullable itemCategories;
@property (nonatomic, strong) NSSet * _Nullable menus;
@end


SWIFT_CLASS_NAMED("Tip")
@interface Tip : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

@interface Tip (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, strong) NSNumber * _Nullable amountInCents;
@property (nonatomic, copy) NSString * _Nullable displayText;
@property (nonatomic) BOOL isCustom;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, strong) Cart * _Nullable cart;
@end


/// A class backed by CoreData that serves as the data layer and source of truth for driving <code>VNOrderUI</code>.
SWIFT_CLASS("_TtC11VNOrderData11VNOrderData")
@interface VNOrderData : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VNOrderData * _Nonnull shared;)
+ (VNOrderData * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface VNOrderData (SWIFT_EXTENSION(VNOrderData))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull classStringName;)
+ (NSString * _Nonnull)classStringName SWIFT_WARN_UNUSED_RESULT;
@end




@interface VNOrderData (SWIFT_EXTENSION(VNOrderData))
- (void)reloadStandsWithCompletion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("Variant")
@interface Variant : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Variant (SWIFT_EXTENSION(VNOrderData))
- (void)addSalesObject:(Sale * _Nonnull)value;
- (void)removeSalesObject:(Sale * _Nonnull)value;
- (void)addSales:(NSSet * _Nonnull)values;
- (void)removeSales:(NSSet * _Nonnull)values;
@end




@interface Variant (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable availableAt;
@property (nonatomic, copy) NSString * _Nullable categoryName;
@property (nonatomic) int64_t defaultQuantity;
@property (nonatomic, copy) NSString * _Nullable eventName;
@property (nonatomic, copy) NSString * _Nullable eventUUID;
@property (nonatomic) int64_t experiencePrice;
@property (nonatomic, copy) NSString * _Nullable expiresAt;
@property (nonatomic, copy) NSString * _Nullable globaltemId;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable inventoryState;
@property (nonatomic) BOOL isModifier;
@property (nonatomic, copy) NSString * _Nullable linkedMenuItemIdentifier;
@property (nonatomic, copy) NSString * _Nullable merchantId;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int64_t onHandQuantity;
@property (nonatomic) int64_t priceAfterThresholdInCents;
@property (nonatomic) int64_t priceInCents;
@property (nonatomic, copy) NSString * _Nullable productSKU;
@property (nonatomic) int64_t purchaseLimit;
@property (nonatomic, copy) NSString * _Nullable redemptionStartsAt;
@property (nonatomic, copy) NSString * _Nullable saleId;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable saleIds;
@property (nonatomic, strong) Item * _Nullable item;
@property (nonatomic, strong) ModifierItem * _Nullable modifierItem;
@property (nonatomic, strong) NSSet * _Nullable sales;
@end


SWIFT_CLASS_NAMED("Venue")
@interface Venue : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Venue (SWIFT_EXTENSION(VNOrderData))
@property (nonatomic, copy) NSString * _Nullable displayName;
@property (nonatomic, copy) NSString * _Nullable organizationName;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
