#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import VNAnalytics;
@import VNCore;
@import VNCoreUI;
@import VNOrderData;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VNOrderUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC9VNOrderUI19MenuItemInteraction")
@interface MenuItemInteraction : AnalyticsEvent
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI12AddItemEvent")
@interface AddItemEvent : MenuItemInteraction
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@end

@class NSCoder;
@class NSBundle;

SWIFT_CLASS("_TtC9VNOrderUI25BottomSheetViewController")
@interface BottomSheetViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class UITableViewCell;

@interface BottomSheetViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9VNOrderUI27CheckoutTableViewController")
@interface CheckoutTableViewController : UITableViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end








@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
@end



@class UITextField;

@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <RoundedTextFieldViewDelegate>
- (void)didFinishEditingWithText:(NSString * _Nonnull)text textField:(UITextField * _Nonnull)textField;
- (void)didChangeTextWithText:(NSString * _Nonnull)text textField:(UITextField * _Nonnull)textField;
@end




@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@protocol PaymentMethodRepresentable;
@class OrderSummary;
@class NSError;

SWIFT_PROTOCOL("_TtP9VNOrderUI35CheckoutTableViewControllerDelegate_")
@protocol CheckoutTableViewControllerDelegate
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC9VNOrderUI14ExperienceCard")
@interface ExperienceCard : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC9VNOrderUI25ExperiencesViewController")
@interface ExperiencesViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ExperiencesViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC9VNOrderUI15ItemDetailEvent")
@interface ItemDetailEvent : MenuItemInteraction
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@end


SWIFT_CLASS("_TtC9VNOrderUI21LineItemTableViewCell")
@interface LineItemTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9VNOrderUI25MarketplaceViewController")
@interface MarketplaceViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end





SWIFT_CLASS("_TtC9VNOrderUI22MetadataViewController")
@interface MetadataViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UIPageViewController;

@interface MetadataViewController (SWIFT_EXTENSION(VNOrderUI)) <UIPageViewControllerDataSource, UIPageViewControllerDelegate>
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerBeforeViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerAfterViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)presentationCountForPageViewController:(UIPageViewController * _Nonnull)pageViewController SWIFT_WARN_UNUSED_RESULT;
- (void)pageViewController:(UIPageViewController * _Nonnull)pageViewController didFinishAnimating:(BOOL)finished previousViewControllers:(NSArray<UIViewController *> * _Nonnull)previousViewControllers transitionCompleted:(BOOL)completed;
@end





@class UINavigationController;
@protocol PaymentProcessable;

SWIFT_CLASS("_TtC9VNOrderUI16OrderCoordinator")
@interface OrderCoordinator : NSObject
@property (nonatomic, readonly) BOOL wasStarted;
@property (nonatomic, strong) UIViewController * _Null_unspecified rootViewController;
/// The navigation controller that was passed in or that was created by the coordinator.
/// If you wish to display the view from a UITabBarController, Hamburger Menu, or present modally,
/// you should let the coordinator create a navigationController (don’t pass one in),
/// and present the navigationController property. Otherwise, when pushing onto your own navigation stack,
/// you should pass in your UINavigationController, call <code>start()</code> then <code>pushViewController()</code>
@property (nonatomic, strong) UINavigationController * _Null_unspecified navigationController;
/// Creates a new coordinator using the VNPaymentProcessor.shared and an automatically created UINavigationController.
- (nonnull instancetype)init;
/// Creates a new coordinator.
/// \param navigationController The navigation controller to use when pushing the view controller.
///
/// \param paymentProcessor The PaymentProcessable object to use for processing payments. Defaults to VNPaymentProcessor.shared.
///
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nullable)navigationController paymentProcessor:(id <PaymentProcessable> _Nullable)paymentProcessor OBJC_DESIGNATED_INITIALIZER;
/// Starts the coordinator. Ensure to call <code>start()</code> after initialization.
/// Not calling <code>start()</code> is a programmer error and will fatalError. Calling <code>start()</code> multiple times will also fatalError.
- (void)start;
@end










@interface OrderCoordinator (SWIFT_EXTENSION(VNOrderUI)) <CheckoutTableViewControllerDelegate>
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end






@interface OrderCoordinator (SWIFT_EXTENSION(VNOrderUI))
- (void)showExperiencesMenuFor:(NSString * _Nonnull)menuUUID;
- (void)pushRvCListWithTitle:(NSString * _Nullable)title;
/// Presents the StandMenuViewController from a presenter.
/// \param menuUUID The UUID of the menu to present.
///
/// \param parent The view controller to present from.
///
/// \param completion The closure to execute after the presentation finishes. This closure has no return value and takes no parameters. You may specify nil for this parameter.
///
- (void)presentMenuFor:(NSString * _Nonnull)menuUUID from:(UIViewController * _Nonnull)parent completion:(void (^ _Nullable)(void))completion;
/// Pushes the StandMenuViewController onto your UINavigationController stack.
/// Ensure you pass in a UINavigationController during init.
/// Calling this without initializing with a navigation controller is a programmer error and will fatalError.
/// \param menuUUID The UUID of the menu to present.
///
- (void)pushMenuFor:(NSString * _Nonnull)menuUUID;
/// Dismisses the presented view controller.
- (void)dismiss;
@end

@class ExperienceItem;

/// The coordinator for displaying Order History.
/// Ensure to call <code>start()</code> after initializing. Not calling <code>start()</code> is a programmer error and will fatalError.
/// Ensure to hold onto the coordinator strongly.
/// It is a progammer error to initialize this coordinator in the context of a method and not retain it. e.g
/// \code
/// // Good
/// class MyClass {
///    let orderHistoryCoordinator: OrderHistoryCoordinator
///
///    init() {
///        self.orderHistoryCoordinator = OrderHistoryCoordinator()
///    }
/// }
///
/// // Bad
/// func showOrderHistory() {
///    let coordinator = OrderHistoryCorrdinator()
///
///    coordinator.present(from: self)
/// }
///
/// \endcodeYou can access the coordinators <code>navigationController</code> property to display the view after calling <code>start()</code>.
/// <h2>Showing on a UITabBarController:</h2>
/// \code
/// class TabBarController: UITabBarController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator() // Don't pass in a navigationController
///         orderHistoryCoordinator.start()
///         orderHistoryCoordinator.navigationController.tabBarItem = ...
///
///         viewControllers = [orderHistoryCoordinator.navigationController!]
///     }
/// }
///
/// \endcode<h2>Pushing onto your UINavigationController:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator(navigationController: self.navigationController!) // Ensure to pass in a navigationController
///         orderHistoryCoordinator.start()
///     }
///
///     func pushOrderHistory() {
///        orderHistoryCoordinator.pushViewController()
///     }
/// }
///
/// \endcode<h2>Presenting modally:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator() // Passing in a navigationController is optional. The coordinator won't use it if presenting modally.
///         orderHistoryCoordinator.start()
///     }
///
///     func presentOrderHistory() {
///        orderHistoryCoordinator.present(from: self)
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC9VNOrderUI23OrderHistoryCoordinator")
@interface OrderHistoryCoordinator : NSObject
/// The navigation controller that was passed in or that was created by the coordinator.
/// If you wish to display the view from a UITabBarController, Hamburger Menu, or present modally,
/// you should let the coordinator create a navigationController (don’t pass one in),
/// and present the navigationController property. Otherwise, when pushing onto your own navigation stack,
/// you should pass in your UINavigationController, call <code>start()</code> then <code>pushViewController()</code>
@property (nonatomic, strong) UINavigationController * _Null_unspecified navigationController;
/// Creates a new coordinator.
/// \param navigationController The navigation controller to use when pushing the view controller and presenting child viewControllers.
///
/// \param paymentProcessor The PaymentProcessable object to use for processing payments. Defaults to VNPaymentProcessor.shared.
///
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nullable)navigationController paymentProcessor:(id <PaymentProcessable> _Nullable)paymentProcessor OBJC_DESIGNATED_INITIALIZER;
/// Starts the coordinator. Ensure to call <code>start()</code> after initialization. Not calling <code>start()</code> is a programmer error and will fatalError.
- (void)start;
/// Pushes the view controller onto your UINavigationController stack.
/// Ensure you pass in a UINavigationController during init.
/// Calling this without initializing with a navigation controller is a programmer error and will fatalError.
- (void)pushViewController;
/// Presents the view controller from a presenter.
/// \param presenter The view controller to present from.
///
/// \param completion The closure to execute after the presentation finishes. This closure has no return value and takes no parameters. You may specify nil for this parameter.
///
- (void)presentFrom:(UIViewController * _Nonnull)presenter completion:(void (^ _Nullable)(void))completion;
+ (void)presentReceiptFrom:(UIViewController * _Nonnull)presenter experiences:(NSArray<ExperienceItem *> * _Nonnull)experiences completion:(void (^ _Nullable)(void))completion;
/// Dismisses the presented view controller.
- (void)dismiss;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface OrderHistoryCoordinator (SWIFT_EXTENSION(VNOrderUI)) <CheckoutTableViewControllerDelegate>
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC9VNOrderUI26OrderHistoryViewController")
@interface OrderHistoryViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDelegate>
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end


SWIFT_CLASS("_TtC9VNOrderUI16OrderStatusEvent")
@interface OrderStatusEvent : AnalyticsEvent
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI16PaymentTypeEvent")
@interface PaymentTypeEvent : AnalyticsEvent
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The coordinator for displaying an orders receipt.
/// This coordinator can <em>only</em> be presented modally. Calling <code>start()</code> will present on presenter modally.
/// If using <code>init(orderUUID:presenter:completion:)</code>, make sure you don’t attempt to <code>start()</code> until the completion closure is called with a success.
/// Ensure to hold onto the coordinator strongly.
/// It is a progammer error to initialize this coordinator in the context of a method and not retain it. e.g
/// \code
/// // Good
/// class MyClass {
///     let receiptCoordinator: RecieptCoordinator
///
///     init() {
///        receiptCoordinator = RecieptCoordinator(...)
///     }
/// }
///
/// // Bad
/// func showOrderHistory() {
///     let coordinator = RecieptCoordinator(...)
///
///     coordinator.start()
/// }
///
/// \endcode<h2>Presenting modally:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var receiptCoordinator: RecieptCoordinator!
///
///     override func viewDidLoad() {
///         receiptCoordinator = RecieptCoordinator(...)
///     }
///
///     func presentOrderHistory() {
///        receiptCoordinator.start()
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC9VNOrderUI18ReceiptCoordinator")
@interface ReceiptCoordinator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI31RichCheckoutTableViewController")
@interface RichCheckoutTableViewController : CheckoutTableViewController
- (void)viewDidLoad;
- (void)onDismiss;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9VNOrderUI28StandMenuTableViewController")
@interface StandMenuTableViewController : UITableViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)reloadData;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIScrollView;

@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (BOOL)scrollViewShouldScrollToTop:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
@end

@protocol NSFetchedResultsSectionInfo;

@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerWillChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
@end


@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end


SWIFT_CLASS("_TtC9VNOrderUI23StandMenuViewController")
@interface StandMenuViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
@end

@class UICollectionView;

@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@class UICollectionViewCell;

@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end




@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@class UILabel;
@class UIImageView;

SWIFT_CLASS("_TtC9VNOrderUI18StandTableViewCell")
@interface StandTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified standImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified detailLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9VNOrderUI25StandsTableViewController")
@interface StandsTableViewController : UITableViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end




@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerWillChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@class UIColor;

SWIFT_CLASS("_TtC9VNOrderUI9TimerCard")
@interface TimerCard : UIView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
/// Calls the <code>onDimiss</code> closure.
- (void)dismiss;
@end














@interface UINavigationController (SWIFT_EXTENSION(VNOrderUI))
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end


















@interface UIViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)dismissKeyboard;
@end






SWIFT_CLASS("_TtC9VNOrderUI7VNOrder")
@interface VNOrder : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VNOrder * _Nonnull shared;)
+ (VNOrder * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VNOrder (SWIFT_EXTENSION(VNOrderUI)) <VNOrderProtocol>
- (void)enableWalletWithWallet:(id _Nonnull)wallet;
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#else
// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import VNAnalytics;
@import VNCore;
@import VNCoreUI;
@import VNOrderData;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VNOrderUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC9VNOrderUI19MenuItemInteraction")
@interface MenuItemInteraction : AnalyticsEvent
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI12AddItemEvent")
@interface AddItemEvent : MenuItemInteraction
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@end

@class NSCoder;
@class NSBundle;

SWIFT_CLASS("_TtC9VNOrderUI25BottomSheetViewController")
@interface BottomSheetViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class UITableViewCell;

@interface BottomSheetViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9VNOrderUI27CheckoutTableViewController")
@interface CheckoutTableViewController : UITableViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end








@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
@end



@class UITextField;

@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <RoundedTextFieldViewDelegate>
- (void)didFinishEditingWithText:(NSString * _Nonnull)text textField:(UITextField * _Nonnull)textField;
- (void)didChangeTextWithText:(NSString * _Nonnull)text textField:(UITextField * _Nonnull)textField;
@end




@interface CheckoutTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@protocol PaymentMethodRepresentable;
@class OrderSummary;
@class NSError;

SWIFT_PROTOCOL("_TtP9VNOrderUI35CheckoutTableViewControllerDelegate_")
@protocol CheckoutTableViewControllerDelegate
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC9VNOrderUI14ExperienceCard")
@interface ExperienceCard : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
@end


SWIFT_CLASS("_TtC9VNOrderUI25ExperiencesViewController")
@interface ExperiencesViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ExperiencesViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC9VNOrderUI15ItemDetailEvent")
@interface ItemDetailEvent : MenuItemInteraction
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@end


SWIFT_CLASS("_TtC9VNOrderUI21LineItemTableViewCell")
@interface LineItemTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9VNOrderUI25MarketplaceViewController")
@interface MarketplaceViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end





SWIFT_CLASS("_TtC9VNOrderUI22MetadataViewController")
@interface MetadataViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class UIPageViewController;

@interface MetadataViewController (SWIFT_EXTENSION(VNOrderUI)) <UIPageViewControllerDataSource, UIPageViewControllerDelegate>
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerBeforeViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)pageViewController:(UIPageViewController * _Nonnull)pageViewController viewControllerAfterViewController:(UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)presentationCountForPageViewController:(UIPageViewController * _Nonnull)pageViewController SWIFT_WARN_UNUSED_RESULT;
- (void)pageViewController:(UIPageViewController * _Nonnull)pageViewController didFinishAnimating:(BOOL)finished previousViewControllers:(NSArray<UIViewController *> * _Nonnull)previousViewControllers transitionCompleted:(BOOL)completed;
@end





@class UINavigationController;
@protocol PaymentProcessable;

SWIFT_CLASS("_TtC9VNOrderUI16OrderCoordinator")
@interface OrderCoordinator : NSObject
@property (nonatomic, readonly) BOOL wasStarted;
@property (nonatomic, strong) UIViewController * _Null_unspecified rootViewController;
/// The navigation controller that was passed in or that was created by the coordinator.
/// If you wish to display the view from a UITabBarController, Hamburger Menu, or present modally,
/// you should let the coordinator create a navigationController (don’t pass one in),
/// and present the navigationController property. Otherwise, when pushing onto your own navigation stack,
/// you should pass in your UINavigationController, call <code>start()</code> then <code>pushViewController()</code>
@property (nonatomic, strong) UINavigationController * _Null_unspecified navigationController;
/// Creates a new coordinator using the VNPaymentProcessor.shared and an automatically created UINavigationController.
- (nonnull instancetype)init;
/// Creates a new coordinator.
/// \param navigationController The navigation controller to use when pushing the view controller.
///
/// \param paymentProcessor The PaymentProcessable object to use for processing payments. Defaults to VNPaymentProcessor.shared.
///
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nullable)navigationController paymentProcessor:(id <PaymentProcessable> _Nullable)paymentProcessor OBJC_DESIGNATED_INITIALIZER;
/// Starts the coordinator. Ensure to call <code>start()</code> after initialization.
/// Not calling <code>start()</code> is a programmer error and will fatalError. Calling <code>start()</code> multiple times will also fatalError.
- (void)start;
@end










@interface OrderCoordinator (SWIFT_EXTENSION(VNOrderUI)) <CheckoutTableViewControllerDelegate>
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end






@interface OrderCoordinator (SWIFT_EXTENSION(VNOrderUI))
- (void)showExperiencesMenuFor:(NSString * _Nonnull)menuUUID;
- (void)pushRvCListWithTitle:(NSString * _Nullable)title;
/// Presents the StandMenuViewController from a presenter.
/// \param menuUUID The UUID of the menu to present.
///
/// \param parent The view controller to present from.
///
/// \param completion The closure to execute after the presentation finishes. This closure has no return value and takes no parameters. You may specify nil for this parameter.
///
- (void)presentMenuFor:(NSString * _Nonnull)menuUUID from:(UIViewController * _Nonnull)parent completion:(void (^ _Nullable)(void))completion;
/// Pushes the StandMenuViewController onto your UINavigationController stack.
/// Ensure you pass in a UINavigationController during init.
/// Calling this without initializing with a navigation controller is a programmer error and will fatalError.
/// \param menuUUID The UUID of the menu to present.
///
- (void)pushMenuFor:(NSString * _Nonnull)menuUUID;
/// Dismisses the presented view controller.
- (void)dismiss;
@end

@class ExperienceItem;

/// The coordinator for displaying Order History.
/// Ensure to call <code>start()</code> after initializing. Not calling <code>start()</code> is a programmer error and will fatalError.
/// Ensure to hold onto the coordinator strongly.
/// It is a progammer error to initialize this coordinator in the context of a method and not retain it. e.g
/// \code
/// // Good
/// class MyClass {
///    let orderHistoryCoordinator: OrderHistoryCoordinator
///
///    init() {
///        self.orderHistoryCoordinator = OrderHistoryCoordinator()
///    }
/// }
///
/// // Bad
/// func showOrderHistory() {
///    let coordinator = OrderHistoryCorrdinator()
///
///    coordinator.present(from: self)
/// }
///
/// \endcodeYou can access the coordinators <code>navigationController</code> property to display the view after calling <code>start()</code>.
/// <h2>Showing on a UITabBarController:</h2>
/// \code
/// class TabBarController: UITabBarController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator() // Don't pass in a navigationController
///         orderHistoryCoordinator.start()
///         orderHistoryCoordinator.navigationController.tabBarItem = ...
///
///         viewControllers = [orderHistoryCoordinator.navigationController!]
///     }
/// }
///
/// \endcode<h2>Pushing onto your UINavigationController:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator(navigationController: self.navigationController!) // Ensure to pass in a navigationController
///         orderHistoryCoordinator.start()
///     }
///
///     func pushOrderHistory() {
///        orderHistoryCoordinator.pushViewController()
///     }
/// }
///
/// \endcode<h2>Presenting modally:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var orderHistoryCoordinator: OrderHistoryCoordinator!
///
///     override func viewDidLoad() {
///         orderHistoryCoordinator = OrderHistoryCoordinator() // Passing in a navigationController is optional. The coordinator won't use it if presenting modally.
///         orderHistoryCoordinator.start()
///     }
///
///     func presentOrderHistory() {
///        orderHistoryCoordinator.present(from: self)
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC9VNOrderUI23OrderHistoryCoordinator")
@interface OrderHistoryCoordinator : NSObject
/// The navigation controller that was passed in or that was created by the coordinator.
/// If you wish to display the view from a UITabBarController, Hamburger Menu, or present modally,
/// you should let the coordinator create a navigationController (don’t pass one in),
/// and present the navigationController property. Otherwise, when pushing onto your own navigation stack,
/// you should pass in your UINavigationController, call <code>start()</code> then <code>pushViewController()</code>
@property (nonatomic, strong) UINavigationController * _Null_unspecified navigationController;
/// Creates a new coordinator.
/// \param navigationController The navigation controller to use when pushing the view controller and presenting child viewControllers.
///
/// \param paymentProcessor The PaymentProcessable object to use for processing payments. Defaults to VNPaymentProcessor.shared.
///
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nullable)navigationController paymentProcessor:(id <PaymentProcessable> _Nullable)paymentProcessor OBJC_DESIGNATED_INITIALIZER;
/// Starts the coordinator. Ensure to call <code>start()</code> after initialization. Not calling <code>start()</code> is a programmer error and will fatalError.
- (void)start;
/// Pushes the view controller onto your UINavigationController stack.
/// Ensure you pass in a UINavigationController during init.
/// Calling this without initializing with a navigation controller is a programmer error and will fatalError.
- (void)pushViewController;
/// Presents the view controller from a presenter.
/// \param presenter The view controller to present from.
///
/// \param completion The closure to execute after the presentation finishes. This closure has no return value and takes no parameters. You may specify nil for this parameter.
///
- (void)presentFrom:(UIViewController * _Nonnull)presenter completion:(void (^ _Nullable)(void))completion;
+ (void)presentReceiptFrom:(UIViewController * _Nonnull)presenter experiences:(NSArray<ExperienceItem *> * _Nonnull)experiences completion:(void (^ _Nullable)(void))completion;
/// Dismisses the presented view controller.
- (void)dismiss;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface OrderHistoryCoordinator (SWIFT_EXTENSION(VNOrderUI)) <CheckoutTableViewControllerDelegate>
- (void)onPaymentCompletionWithOrderSummary:(OrderSummary * _Nullable)orderSummary productType:(enum ProductType)productType error:(NSError * _Nullable)error;
- (void)onPayNow:(CheckoutTableViewController * _Nullable)viewController productType:(enum ProductType)productType completion:(void (^ _Nonnull)(id <PaymentMethodRepresentable> _Nullable, NSError * _Nullable))completion;
- (void)postPaymentMethod:(id <PaymentMethodRepresentable> _Nonnull)paymentMethod completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC9VNOrderUI26OrderHistoryViewController")
@interface OrderHistoryViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <UITableViewDelegate>
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderHistoryViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end


SWIFT_CLASS("_TtC9VNOrderUI16OrderStatusEvent")
@interface OrderStatusEvent : AnalyticsEvent
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI16PaymentTypeEvent")
@interface PaymentTypeEvent : AnalyticsEvent
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The coordinator for displaying an orders receipt.
/// This coordinator can <em>only</em> be presented modally. Calling <code>start()</code> will present on presenter modally.
/// If using <code>init(orderUUID:presenter:completion:)</code>, make sure you don’t attempt to <code>start()</code> until the completion closure is called with a success.
/// Ensure to hold onto the coordinator strongly.
/// It is a progammer error to initialize this coordinator in the context of a method and not retain it. e.g
/// \code
/// // Good
/// class MyClass {
///     let receiptCoordinator: RecieptCoordinator
///
///     init() {
///        receiptCoordinator = RecieptCoordinator(...)
///     }
/// }
///
/// // Bad
/// func showOrderHistory() {
///     let coordinator = RecieptCoordinator(...)
///
///     coordinator.start()
/// }
///
/// \endcode<h2>Presenting modally:</h2>
/// \code
/// class MyViewController: UIViewController {
///     var receiptCoordinator: RecieptCoordinator!
///
///     override func viewDidLoad() {
///         receiptCoordinator = RecieptCoordinator(...)
///     }
///
///     func presentOrderHistory() {
///        receiptCoordinator.start()
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC9VNOrderUI18ReceiptCoordinator")
@interface ReceiptCoordinator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9VNOrderUI31RichCheckoutTableViewController")
@interface RichCheckoutTableViewController : CheckoutTableViewController
- (void)viewDidLoad;
- (void)onDismiss;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9VNOrderUI28StandMenuTableViewController")
@interface StandMenuTableViewController : UITableViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)reloadData;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIScrollView;

@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (BOOL)scrollViewShouldScrollToTop:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
@end

@protocol NSFetchedResultsSectionInfo;

@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerWillChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
@end


@interface StandMenuTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end


SWIFT_CLASS("_TtC9VNOrderUI23StandMenuViewController")
@interface StandMenuViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
@end

@class UICollectionView;

@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@class UICollectionViewCell;

@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end




@interface StandMenuViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@class UILabel;
@class UIImageView;

SWIFT_CLASS("_TtC9VNOrderUI18StandTableViewCell")
@interface StandTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified standImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified detailLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9VNOrderUI25StandsTableViewController")
@interface StandsTableViewController : UITableViewController
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end




@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI))
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI)) <NSFetchedResultsControllerDelegate>
- (void)controllerWillChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
@end


@interface StandsTableViewController (SWIFT_EXTENSION(VNOrderUI)) <PageViewTrackable>
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewName;
@property (nonatomic, readonly, copy) NSString * _Nonnull pageViewTitle;
@end

@class UIColor;

SWIFT_CLASS("_TtC9VNOrderUI9TimerCard")
@interface TimerCard : UIView
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
/// Calls the <code>onDimiss</code> closure.
- (void)dismiss;
@end














@interface UINavigationController (SWIFT_EXTENSION(VNOrderUI))
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end


















@interface UIViewController (SWIFT_EXTENSION(VNOrderUI))
- (void)dismissKeyboard;
@end






SWIFT_CLASS("_TtC9VNOrderUI7VNOrder")
@interface VNOrder : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VNOrder * _Nonnull shared;)
+ (VNOrder * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface VNOrder (SWIFT_EXTENSION(VNOrderUI)) <VNOrderProtocol>
- (void)enableWalletWithWallet:(id _Nonnull)wallet;
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
